version: '3.6'

services:
  nodered:
#    image: ctmagazin/ctnodered:latest
    image: testing:node-red-build
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    restart: always
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mqtt:/mosquitto
      - /etc/localtime:/etc/localtime
    restart: always
    environment:
      - TZ=Europe/Berlin
    
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Berlin

  zigbeeadmin:
    image: carldebilly/zigbee2mqttassistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mqtt
      - TZ=Europe/Berlin
    ports:
      - 8880:80
    restart: unless-stopped